--- 
name: brightscript
https://github.com/pubnub/brightscript
version: "4.0.0"
schema: 1
changelog: 
features: 
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-SET-STATE
    - PRESENCE-GET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-COMPRESS-MESSAGE    
    - PUBLISH-ASYNC
    - PUBLISH-REPLICATION-FLAG
    - PUBLISH-MESSAGE-TTL
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNELS-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
    - SUBSCRIBE-MESSAGE-DEDUPE
  unsubscribe:
    - UNSUBSCRIBE-ALL